---

- name: Set hostname
  become: yes
  hostname:
    name: "{{ hostname }}"
    use: debian

- name: Set hostname in /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: ^127\.0\.1\.1
    line: "{{ '127.0.1.1	' + hostname }}"