---

- name: Create SSH keys for user
  shell:
    cmd: 'ssh-keygen -q -t rsa -f /home/{{ pi_user_username }}/.ssh/id_rsa -C "" -N ""'
    creates: "/home/{{ pi_user_username }}/.ssh/id_rsa"

- name: Add keychain to .bashrc
  lineinfile:
    create: yes
    path: "{{ '/home/' + pi_username + '/.bashrc' }}"
    line: eval `keychain --eval --agents ssh id_rsa`

- name: Add SSH key to nodes
  include_tasks: "add-ssh-key-to-nodes.yml"
  vars:
    host: "{{ item }}"
  with_items: "{{ groups['nodes'] }}"