---

- name: Add clusterhat start script
  become: yes
  copy:
    src: clusterhat-start-nodes
    dest: /sbin/clusterhat-start-nodes
    owner: root
    group: root
    mode: 0755

- name: Add clusterhat node service
  become: yes
  copy:
    src: clusterhat-nodes.service
    dest: /etc/systemd/system/clusterhat-nodes.service
    owner: root
    group: root
    mode: 0644

- name: Enable clusterhat node service
  become: yes
  systemd:
    name: clusterhat-nodes
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for nodes to start
  wait_for:
    host: "{{ item }}"
    port: 22
  with_items: "{{ groups['nodes'] }}"