---

- name: Install packages
  become: yes
  apt:
    name: "{{ apt_packages }}"
    state: present

- name: Install Python packages
  become: true
  pip:
    name: "{{ pip_packages }}"

- name: Upgrade packages
  become: yes
  apt:
    update-cache: yes
    upgrade: full