---

- name: Add docker repository key
  become: yes
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/raspbian/gpg

- name: Add docker repository
  become: yes
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
    state: present

- name: Install docker apt packages
  become: yes
  apt:
    name: "{{ apt_packages }}"
    install_recommends: no

- name: Install docker python packages
  become: yes
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ pip_packages }}"

- name: Add '{{ pi_user_username }}' to docker group
  become: yes
  user:
    name: '{{ pi_user_username }}'
    groups: docker
    append: yes